name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install Wget
        run: sudo apt install -y wget

      - name: Download Forge
        run: wget -q https://github.com/themeliolabs/artifacts/raw/master/forge.tar.gz

      - name: Extract Forge
        run: tar -xf forge.tar.gz

      - name: Remove Forge Archive
        run: rm forge.tar.gz

      - name: Make Forge Executable
        run: chmod +x forge

      - name: Move Forge To A PATH Directory
        run: sudo mv forge /usr/local/bin/forge

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Run Forge Tests
        env:
          RUST_LOG: forge=trace
        run: forge test -vvv --no-match-test FFI