name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Apt
        run: apt update

      - name: Install Wget
        run: apt install -y wget

      - name: Download Forge
        run: wget -q https://github.com/themeliolabs/artifacts/raw/master/forge.tar.gz

      - name: Extract Forge
        run: tar -xf forge.tar.gz

      - name: Remove Forge Archive
        run: rm forge.tar.gz

      - name: Make Forge Executable
        run: chmod +x forge

      - name: Move Forge To A PATH Directory
        run: mv forge /usr/local/bin/forge

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Build Differentials
        working-directory: src/test/differentials
        run: cargo build

      - name: Run Forge Tests
        env:
          RUST_LOG: forge=trace
        run: forge test -vvv --ffi